java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 0
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 1
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 2
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 3
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 4
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 5
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 6
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 7
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 8
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 9
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 10
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 11
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 12
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 13
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 14
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 15
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 16
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 17
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 18
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 19
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 20
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 21
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 22
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 23
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 24
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 25
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 26
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 27
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 28
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 29
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 30
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 31
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 32
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 33
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 34
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 35
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 36
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 37
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 38
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 39
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 40
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 41
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 42
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 43
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 44
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 45
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 46
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 47
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 48
java -cp ./bin:/opt/simgrid-java/java/simgrid.jar mapreducesim/scheduling/test/LocalityTestJobMaker 49
